<script type="text/javascript" src="/admin/lib/jquery/1.9.1/jquery.min.js"></script> 
<script type="text/javascript" src="/admin/lib/layer/2.1/layer.js"></script>
<script type="text/javascript" src="/admin/lib/icheck/jquery.icheck.min.js"></script> 
<script type="text/javascript" src="/admin/lib/jquery.validation/1.14.0/jquery.validate.min.js"></script>
<script type="text/javascript" src="/admin/lib/jquery.validation/1.14.0/validate-methods.js"></script>
<script type="text/javascript" src="/admin/lib/jquery.validation/1.14.0/messages_zh.min.js"></script>
<script type="text/javascript" src="/admin/static/h-ui/js/H-ui.js"></script>
<script type="text/javascript" src="/admin/static/h-ui.admin/js/H-ui.admin.js"></script>
<script type="text/javascript" src="/admin/js/vue/vue.js"></script>
<script type="text/javascript" src="/admin/js/vue/vue-validator.js"></script>
<script type="text/javascript" src="/admin/js/vue/vue-resource.js"></script>
<script type="text/javascript" src="/admin/js/vue/vue.lazyload.js"></script>
<script type="text/javascript" src="/admin/lib/My97DatePicker/WdatePicker.js"></script> 
